version: '3.8'

services:
  backend-general:
    image: backend-general:latest
    container_name: backend-general
    environment:
      - AGORA_ADDR=http://agora-token-service:8080
    ports:
      - "8080:8080"
    restart: on-failure

  agora-token-service:
    image: iamriajul/agora-token-service:latest
    container_name: agora-token-service
    environment:
      - APP_ID=a2092044d6ca44ecab0c9a797a677110
      - APP_CERTIFICATE=49bbfec2d89b43ab95ae570e4b101824
      - CORS_ALLOW_ORIGIN=*
    restart: on-failure